name             'stig-iis'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures stig-iis'
long_description 'Installs/Configures stig-iis'
version          '0.1.0'

depends 'windows'
depends 'iis'